// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWBe8CEZMH06Q15pF_PkGNW13rvMtCCLQ',
    appId: '1:776919120770:web:99d3632d1e049b279bad9b',
    messagingSenderId: '776919120770',
    projectId: 'shoelab-fyp-f73e3',
    authDomain: 'shoelab-fyp-f73e3.firebaseapp.com',
    storageBucket: 'shoelab-fyp-f73e3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo7T3F8fSiuFIcYuAduAKJLZ5Gqewr5ww',
    appId: '1:776919120770:android:88124f9046f2fe2c9bad9b',
    messagingSenderId: '776919120770',
    projectId: 'shoelab-fyp-f73e3',
    storageBucket: 'shoelab-fyp-f73e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu8ou69WmV_f3Mho9Y0Br-llx8VZ5huIg',
    appId: '1:776919120770:ios:ba32ea8a826e8a939bad9b',
    messagingSenderId: '776919120770',
    projectId: 'shoelab-fyp-f73e3',
    storageBucket: 'shoelab-fyp-f73e3.appspot.com',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu8ou69WmV_f3Mho9Y0Br-llx8VZ5huIg',
    appId: '1:776919120770:ios:ba32ea8a826e8a939bad9b',
    messagingSenderId: '776919120770',
    projectId: 'shoelab-fyp-f73e3',
    storageBucket: 'shoelab-fyp-f73e3.appspot.com',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWBe8CEZMH06Q15pF_PkGNW13rvMtCCLQ',
    appId: '1:776919120770:web:4a83a75ffe7faaf59bad9b',
    messagingSenderId: '776919120770',
    projectId: 'shoelab-fyp-f73e3',
    authDomain: 'shoelab-fyp-f73e3.firebaseapp.com',
    storageBucket: 'shoelab-fyp-f73e3.appspot.com',
  );
}
